<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="dispositivo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="movil"  maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="marca" type="xs:string" use="required" />
						<xs:attribute name="modelo" type="xs:string" use="required" />
						<xs:attribute name="precio" type="xs:decimal" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="television">
					<xs:complexType>
						<xs:attribute name="marca" type="xs:string" use="required" />
						<xs:attribute name="modelo" type="xs:string" use="required" />
						<xs:attribute name="precio" type="xs:decimal" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
